### ISSUE TITLE
Catkinize sicktoolbox_wrapper

### ISSUE THREAD

**Issue by chadrockey** [ros-drivers/sicktoolbox_wrapper#1]
Sicktoolbox_wrapper and sicktoolbox need catkinized.

It's probably best to make sicktoolbox like a system dependency.  We should also look at switching to version 1.01.  I think the consensus is that we're just going to fork sicktoolbox to our own hosting and apply patches through github.

Sicktoolbox has a pretty complicated build system, so I'll need help getting it released for Hydro.  @wjwwood @dirk-thomas   :)

**Comment by wjwwood** [comment]
I am working on converting sicktoolbox trunk to CMake, in between builds of
workspaces and other bits of downtime.

## 

On Thu, Jan 24, 2013 at 1:52 PM, Chad Rockey notifications@github.comwrote:

> Sicktoolbox_wrapper and sicktoolbox need catkinized.
> 
> It's probably best to make sicktoolbox like a system dependency. We should
> also look at switching to version 1.01. I think the consensus is that we're
> just going to fork sicktoolbox to our own hosting and apply patches through
> github.
> 
> Sicktoolbox has a pretty complicated build system, so I'll need help
> getting it released for Hydro. @wjwwood https://github.com/wjwwood
> @dirk-thomas https://github.com/dirk-thomas :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ros-drivers/sicktoolbox_wrapper/issues/1.

## 

William Woodall
Willow Garage - Software Engineer
wwoodall@willowgarage.com

**Comment by trainman419** [comment]
This is done. Closing.
